######################################################################
# Automatically generated by qmake (3.0) Mon Dec 7 09:47:07 2015
######################################################################

TEMPLATE = app
TARGET = readPicture
INCLUDEPATH += .
LIBS +=
QT += widgets
CONFIG += link_pkgconfig
PKGCONFIG += opencv

# Input
SOURCES += readPicture.cpp
